server:
  port: 8800
spring:
  application:
    name: ZCY_USER_SERVICE
  cloud:
    zookeeper:
      discovery:
        root: spring-cloud-service
      connect-string: zookeeper1.configure.com:10011,zookeeper2.configure.com:10011,zookeeper3.configure.com:10011
