server:
  port: 8091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhao200810828/zcy-spring-cloud-config-resp
          search-paths: /**
        default-application-name: configServer
      label: master
      username: zhao200810828
      password: zhao626597
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/